export enum GameActions {
  INITIALIZE_GAME = "INITIALIZE_GAME",
  DRAW_INITIAL_CARDS = "DRAW_INITIAL_CARDS",
  PLAY_CARD = "PLAY_CARD",
  CHANGE_PHASE = "CHANGE_PHASE",
  UPDATE_LIFE_POINTS = "UPDATE_LIFE_POINTS",
  ATTACK = "ATTACK",
  END_TURN = "END_TURN",
  SURRENDER = "SURRENDER",
}
